INFO     Bach_WF_F02_Sonate_C-Dur.ms3 -- Attempting to parse Bach_WF_F02_Sonate_C-Dur.mscx
WARNING  Bach_WF_F02_Sonate_C-Dur.ms3 -- MC 65 has 3 TimeSig-nodes. Used first (3/4), ignored ['3/4', '3/4'].
WARNING  Bach_WF_F02_Sonate_C-Dur.ms3 -- MC 109 has 2 TimeSig-nodes. Used first (3/4), ignored ['3/4'].
WARNING  Bach_WF_F02_Sonate_C-Dur.ms3 -- MC 1 has 2 TimeSig-nodes. Used first (4/4), ignored ['4/4'].
WARNING  Bach_WF_F02_Sonate_C-Dur.ms3 -- Voltas overlap in MC [64]
WARNING  Bach_WF_F02_Sonate_C-Dur.ms3 -- Voltas overlap in MC [133]
WARNING  Bach_WF_F02_Sonate_C-Dur.ms3 -- Doublings: mc  onset
99  1/2      iio/iv
    1/2           v
Name: chords, dtype: object
WARNING  Bach_WF_F02_Sonate_C-Dur.ms3 -- MC 21 in volta [21] has not been excluded from barcount.
WARNING  Bach_WF_F02_Sonate_C-Dur.ms3 -- MC 133 in volta [133] has not been excluded from barcount.
WARNING  Bach_WF_F02_Sonate_C-Dur.ms3 -- MC 176 in volta [176] has not been excluded from barcount.
INFO     Bach_WF_F02_Sonate_C-Dur.ms3 -- Done parsing Bach_WF_F02_Sonate_C-Dur.mscx

WARNING  Bach_WF_F02_Sonate_C-Dur.expand_labels -- The following chords could not be parsed:
      mc   mn onset    label
91    33   33     0      V97
93    33   33   1/2    V97/V
133   47   47     0       V"
136   47   47   3/4       I"
210   75   75   1/4    V(4)V
217   78   78   1/8      V97
269   95   95   3/8      V97
297  104  104   1/8      V97
304  106  106     0  iv6(7#)
367  127  127   1/4      V97
416  143  143   1/2      V97
456  153  153   1/2   V97/IV
458  154  154     0   IV(4b)
463  155  155     0   IV(4b)
493  167  167   5/8      V92
501  170  170   1/4      V97
ERROR    Bach_WF_F02_Sonate_C-Dur.expand_labels -- Are you expanding labels of several pieces in the same DataFrame? In that case, define 'groupby()' parameters.
ERROR    Bach_WF_F02_Sonate_C-Dur -- Could not expand labels due to errors:
Traceback (most recent call last):
  File "<ipython-input-11-9ecc4a9db7e3>", line 21, in parse
    expanded = expand_labels(chord_list, column='label', regex=REGEX, chord_tones=True, groupby=None, logger_name=S.fname).df
  File "/home/hentsche/corpora/scripts/expand_labels.py", line 447, in __init__
    df = self.propagate_keys(df, add_bool=True, **key_cols)
  File "/home/hentsche/corpora/scripts/expand_labels.py", line 711, in propagate_keys
    raise NotImplementedError("Several global keys not accepted at the moment.")
NotImplementedError: Several global keys not accepted at the moment.
